# Runs unit and integration tests
name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GO_VERSION: ["1.18.x", "1.19.x", "1.20.x", "1.21.x"]

    steps:
      - uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          cancel_others: true

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ matrix.GO_VERSION }}
          check-latest: true

      - run: go test ./...

      - uses: golangci/golangci-lint-action@v2
        with:
          args: --go=${{ matrix.go-version }}
          skip-go-installation: true
