# Runs unit and integration tests
name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  go-version: 1.18

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          cancel_others: true

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - run: go test ./...

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          cancel_others: true

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - uses: golangci/golangci-lint-action@v2
        with:
          args: --go=${{ env.go-version }}
          skip-go-installation: true
